version: '2.1'

volumes:
  pihole_config:
  dnsmasq_config:
  sense-data:

services:
  pihole:
    build: ./pihole
    privileged: true
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    cap_add:
      - 'NET_ADMIN'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    network_mode: host

  # optional upstream resolver: https://github.com/jedisct1/dnscrypt-proxy
  # set pihole DNS1 and DNS2 service variables to 127.0.0.1:5300 to use this for upstream DNS
  # otherwise comment out this block to completely remove the service
  dnscrypt-proxy:
    build: ./dnscrypt-proxy
    ports:
      - '5300:53/tcp'
      - '5300:53/udp'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'

  influxdb:
    restart: always
    build: ./balena-sense/influxdb
    volumes:
      - 'sense-data:/data'

  grafana:
    restart: always
    build: ./balena-sense/grafana
    ports:
      - "3000:80"
    volumes:
      - 'sense-data:/data'
    environment:
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_PATHS_PROVISIONING=/usr/src/app/provisioning'
        - 'GF_SESSION_PROVIDER=memory'

  sensor:
    build: ./balena-sense/sensor
    privileged: true
    restart: always
    volumes:
      - 'sense-data:/data'

  telegraf:
    build: ./balena-sense/telegraf
    restart: always